<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>rfema: Getting Started • rfema</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="rfema: Getting Started">
<meta property="og:description" content="rfema">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">rfema</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/getting_started.html">rfema: Getting Started</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/dylan-turner25/rfema/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="getting_started_files/header-attrs-2.11/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>rfema: Getting Started</h1>
                        <h4 class="author">Dylan Turner</h4>
            
            <h4 class="date">2021-11-05</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/dylan-turner25/rfema/blob/master/vignettes/getting_started.Rmd"><code>vignettes/getting_started.Rmd</code></a></small>
      <div class="hidden name"><code>getting_started.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This vignette provides a brief overview on using the <code>rfema</code> package to obtain data from the Open FEMA API. The rest of this vignette covers how to install the package, followed by examples on using the package to obtain data for various objectives.</p>
</div>
<div id="installation" class="section level2">
<h2 class="hasAnchor">
<a href="#installation" class="anchor"></a>Installation</h2>
<p>Right now, the best way to install and use the <code>rfema</code> package is by installing directly from GitHub using <code>devtools::install_github("dylan-turner25/rfema")</code>. The FEMA API does not require and API key, meaning no further steps need be taken to start using the package</p>
</div>
<div id="avaliable-datasets" class="section level2">
<h2 class="hasAnchor">
<a href="#avaliable-datasets" class="anchor"></a>Avaliable Datasets</h2>
<p>To see the all of the data sets avaliable through <code>rfema</code>, we can run the <code><a href="../reference/fema_data_sets.html">fema_data_sets()</a></code> function which calls the FEMA API endpoint: <a href="https://www.fema.gov/api/open/v1/DataSets" class="uri">https://www.fema.gov/api/open/v1/DataSets</a>. This returns a data frame containing meta data on the data sets provided through the open FEMA API.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">data_sets</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/fema_data_sets.html">fema_data_sets</a></span><span class="op">(</span><span class="op">)</span> 
<span class="va">data_sets</span><span class="op">$</span><span class="va">description</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/substr.html">substr</a></span><span class="op">(</span><span class="va">data_sets</span><span class="op">$</span><span class="va">description</span>,<span class="fl">1</span>,<span class="fl">50</span><span class="op">)</span>,<span class="st">"..."</span><span class="op">)</span> <span class="co"># description shortened in this case to make table smaller</span>

<span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_sets</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="co"># only displaying first few data sets</span></code></pre></div>
<table class="table">
<colgroup>
<col width="0%">
<col width="2%">
<col width="3%">
<col width="3%">
<col width="5%">
<col width="1%">
<col width="1%">
<col width="5%">
<col width="1%">
<col width="1%">
<col width="5%">
<col width="1%">
<col width="1%">
<col width="5%">
<col width="6%">
<col width="4%">
<col width="1%">
<col width="2%">
<col width="0%">
<col width="1%">
<col width="0%">
<col width="2%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="1%">
<col width="0%">
<col width="0%">
<col width="1%">
<col width="0%">
<col width="1%">
<col width="0%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="0%">
<col width="2%">
<col width="1%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="1%">
<col width="1%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
<col width="0%">
</colgroup>
<thead><tr class="header">
<th align="left">identifier</th>
<th align="left">name</th>
<th align="left">title</th>
<th align="left">description</th>
<th align="left">distribution.accessURL</th>
<th align="left">distribution.format</th>
<th align="left">distribution.datasetSize</th>
<th align="left">distribution.accessURL.1</th>
<th align="left">distribution.format.1</th>
<th align="left">distribution.datasetSize.1</th>
<th align="left">distribution.accessURL.2</th>
<th align="left">distribution.format.2</th>
<th align="left">distribution.datasetSize.2</th>
<th align="left">webService</th>
<th align="left">dataDictionary</th>
<th align="left">keyword</th>
<th align="left">modified</th>
<th align="left">publisher</th>
<th align="left">contactPoint</th>
<th align="left">mbox</th>
<th align="left">accessLevel</th>
<th align="left">landingPage</th>
<th align="left">temporal</th>
<th align="left">api</th>
<th align="left">version</th>
<th align="left">bureauCode</th>
<th align="left">programCode</th>
<th align="left">accessLevelComment</th>
<th align="left">license</th>
<th align="left">spatial</th>
<th align="left">theme</th>
<th align="left">dataQuality</th>
<th align="left">accrualPeriodicity</th>
<th align="left">language</th>
<th align="left">primaryITInvestmentUII</th>
<th align="left">issued</th>
<th align="left">systemOfRecords</th>
<th align="left">deprecated</th>
<th align="left">hash</th>
<th align="left">lastRefresh</th>
<th align="left">recordCount</th>
<th align="left">depApiMessage</th>
<th align="left">depNewURL</th>
<th align="left">depWebMessage</th>
<th align="left">lastDataSetRefresh</th>
<th align="left">id</th>
<th align="left">accessUrl</th>
<th align="left">format</th>
<th align="left">depDate</th>
<th align="left">keyword1</th>
<th align="left">keyword2</th>
<th align="left">keyword3</th>
<th align="left">keyword4</th>
<th align="left">keyword5</th>
<th align="left">keyword6</th>
<th align="left">keyword7</th>
<th align="left">keyword8</th>
<th align="left">keyword9</th>
<th align="left">keyword10</th>
<th align="left">keyword11</th>
<th align="left">keyword12</th>
<th align="left">keyword13</th>
<th align="left">keyword14</th>
<th align="left">references</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">openfema-1</td>
<td align="left">PublicAssistanceFundedProjectsSummaries</td>
<td align="left">Public Assistance Funded Project Summaries</td>
<td align="left">FEMA provides supplemental Federal disaster grant …</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.csv" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.csv</a></td>
<td align="left">csv</td>
<td align="left">small (10MB - 50MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.json" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.json</a></td>
<td align="left">json</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.jsona" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.jsona</a></td>
<td align="left">jsona</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries</a></td>
<td align="left"><a href="https://www.fema.gov/openfema-data-page/public-assistance-funded-projects-summaries-v1" class="uri">https://www.fema.gov/openfema-data-page/public-assistance-funded-projects-summaries-v1</a></td>
<td align="left">public, assistance, disaster, grant, funding, sub-grantees</td>
<td align="left">2019-05-30T04:00:00.000Z</td>
<td align="left">Federal Emergency Management Agency</td>
<td align="left">OpenFEMA</td>
<td align="left"><a href="mailto:openfema@fema.gov" class="email">openfema@fema.gov</a></td>
<td align="left">public</td>
<td align="left"><a href="https://www.fema.gov/assistance/public" class="uri">https://www.fema.gov/assistance/public</a></td>
<td align="left">1980-02-01/</td>
<td align="left">TRUE</td>
<td align="left">1</td>
<td align="left">024:70</td>
<td align="left">024:039</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">Public Assistance</td>
<td align="left">true</td>
<td align="left">R/P1D</td>
<td align="left">en-US</td>
<td align="left"></td>
<td align="left">2010-01-21T05:00:00.000Z</td>
<td align="left"></td>
<td align="left">FALSE</td>
<td align="left">bd507ed0181bba91866372a0a5d3c3e4</td>
<td align="left">2021-11-04T16:35:39.443Z</td>
<td align="left">171279</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">2021-11-04T16:35:39.443Z</td>
<td align="left">5dd723598ca22d24d423eb6f</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">openfema-1</td>
<td align="left">PublicAssistanceFundedProjectsSummaries</td>
<td align="left">Public Assistance Funded Project Summaries</td>
<td align="left">FEMA provides supplemental Federal disaster grant …</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.csv" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.csv</a></td>
<td align="left">csv</td>
<td align="left">small (10MB - 50MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.json" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.json</a></td>
<td align="left">json</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.jsona" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries.jsona</a></td>
<td align="left">jsona</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries" class="uri">https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsSummaries</a></td>
<td align="left"><a href="https://www.fema.gov/openfema-data-page/public-assistance-funded-projects-summaries-v1" class="uri">https://www.fema.gov/openfema-data-page/public-assistance-funded-projects-summaries-v1</a></td>
<td align="left">public, assistance, disaster, grant, funding, sub-grantees</td>
<td align="left">2019-05-30T04:00:00.000Z</td>
<td align="left">Federal Emergency Management Agency</td>
<td align="left">OpenFEMA</td>
<td align="left"><a href="mailto:openfema@fema.gov" class="email">openfema@fema.gov</a></td>
<td align="left">public</td>
<td align="left"><a href="https://www.fema.gov/assistance/public" class="uri">https://www.fema.gov/assistance/public</a></td>
<td align="left">1980-02-01/</td>
<td align="left">TRUE</td>
<td align="left">1</td>
<td align="left">024:70</td>
<td align="left">024:039</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">Public Assistance</td>
<td align="left">true</td>
<td align="left">R/P1D</td>
<td align="left">en-US</td>
<td align="left"></td>
<td align="left">2010-01-21T05:00:00.000Z</td>
<td align="left"></td>
<td align="left">FALSE</td>
<td align="left">bd507ed0181bba91866372a0a5d3c3e4</td>
<td align="left">2021-11-04T16:35:39.443Z</td>
<td align="left">171279</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">2021-11-04T16:35:39.443Z</td>
<td align="left">5dd723598ca22d24d423eb6f</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">openfema-26</td>
<td align="left">FemaWebDeclarationAreas</td>
<td align="left">FEMA Web Declaration Areas</td>
<td align="left">This data set contains general information on decl…</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas.csv" class="uri">https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas.csv</a></td>
<td align="left">csv</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas.json" class="uri">https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas.json</a></td>
<td align="left">json</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas.jsona" class="uri">https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas.jsona</a></td>
<td align="left">jsona</td>
<td align="left">medium (50MB - 500MB)</td>
<td align="left"><a href="https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas" class="uri">https://www.fema.gov/api/open/v1/FemaWebDeclarationAreas</a></td>
<td align="left"><a href="https://www.fema.gov/openfema-data-page/fema-web-declaration-areas-v1" class="uri">https://www.fema.gov/openfema-data-page/fema-web-declaration-areas-v1</a></td>
<td align="left">disaster, declaration, fema website</td>
<td align="left">2019-09-26T04:00:00.000Z</td>
<td align="left">Federal Emergency Management Agency</td>
<td align="left">OpenFEMA</td>
<td align="left"><a href="mailto:openfema@fema.gov" class="email">openfema@fema.gov</a></td>
<td align="left">public</td>
<td align="left"><a href="https://www.fema.gov/disasters" class="uri">https://www.fema.gov/disasters</a></td>
<td align="left">1960-11-01/</td>
<td align="left">TRUE</td>
<td align="left">1</td>
<td align="left">024:70</td>
<td align="left">024:039</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">Disaster Information</td>
<td align="left">true</td>
<td align="left">R/PT20M</td>
<td align="left">en-US</td>
<td align="left"></td>
<td align="left">NA</td>
<td align="left"></td>
<td align="left">FALSE</td>
<td align="left">89eaca0ba42130ddbd5477ed92fee30b</td>
<td align="left">2021-11-05T09:27:59.459Z</td>
<td align="left">438093</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">2021-11-05T09:27:59.459Z</td>
<td align="left">5dd723598ca22d24d423eb73</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="example-workflow" class="section level2">
<h2 class="hasAnchor">
<a href="#example-workflow" class="anchor"></a>Example Workflow</h2>
<p>Once we know what data set we want to access, or perhaps if we want to know more about what data is avaliable in a given data set, we can use the <code><a href="../reference/fema_data_fields.html">fema_data_fields()</a></code> function to get a look at the available data fields in a given data set by setting the “data_set” parameter to one of the “name” columns in the data frame returned by the <code><a href="../reference/fema_data_sets.html">fema_data_sets()</a></code> function.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/fema_data_fields.html">fema_data_fields</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipPolicies"</span><span class="op">)</span>
<span class="va">df</span><span class="op">$</span><span class="va">Description</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/substr.html">substr</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">Description</span>,<span class="fl">1</span>,<span class="fl">50</span><span class="op">)</span>,<span class="st">"..."</span><span class="op">)</span> <span class="co"># description shortened in this case to make table smaller</span>
<span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">df</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<table class="table">
<colgroup>
<col width="0%">
<col width="1%">
<col width="2%">
<col width="0%">
<col width="4%">
<col width="5%">
<col width="57%">
<col width="1%">
<col width="2%">
<col width="0%">
<col width="1%">
<col width="2%">
<col width="1%">
<col width="6%">
<col width="3%">
<col width="3%">
<col width="1%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="left">datasetId</th>
<th align="left">openFemaDataSet</th>
<th align="left">name</th>
<th align="left">title</th>
<th align="left">description</th>
<th align="left">type</th>
<th align="left">sortOrder</th>
<th align="left">datasetVersion</th>
<th align="left">hash</th>
<th align="left">lastRefresh</th>
<th align="left">isNestedObject</th>
<th align="left">isNullable</th>
<th align="left">isSearchable</th>
<th align="left">primaryKey</th>
<th align="left">id</th>
<th align="left">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">698</td>
<td align="left">openfema-32</td>
<td align="left">FimaNfipPolicies</td>
<td align="left">1</td>
<td align="left">agricultureStructureIndicator</td>
<td align="left">Agriculture Structure Indicator</td>
<td align="left">Yes (Y) or No (N) indicator of whether or not a building is reported as being an agricultural structure in the policy application. Yes is indicated with either a ‘true’ or ‘1’. No is indicated with either a ‘false’ or ‘0’</td>
<td align="left">boolean</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left"></td>
<td align="left">aecf8b7e731e842e2e23d83bdd2ac8929f0ce74c</td>
<td align="left">2021-09-01T15:01:27.188Z</td>
<td align="left">5f086f3e1dbf327060c5c0c4</td>
<td align="left">…</td>
</tr>
<tr class="even">
<td align="left">700</td>
<td align="left">openfema-32</td>
<td align="left">FimaNfipPolicies</td>
<td align="left">1</td>
<td align="left">baseFloodElevation</td>
<td align="left">Base Flood Elevation</td>
<td align="left">Base Flood Elevation (BFE) is the elevation at which there is a 1% chance per year of flooding in feet from the elevation certificate</td>
<td align="left">number</td>
<td align="left">2</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="left">TRUE</td>
<td align="left"></td>
<td align="left">4d2c404d25597c49fdadc6ebf9bc4e226d23b6f0</td>
<td align="left">2021-09-01T15:01:27.188Z</td>
<td align="left">5f086f3e1dbf327060c5c0c6</td>
<td align="left">…</td>
</tr>
<tr class="odd">
<td align="left">701</td>
<td align="left">openfema-32</td>
<td align="left">FimaNfipPolicies</td>
<td align="left">1</td>
<td align="left">basementEnclosureCrawlspaceType</td>
<td align="left">Basement Enclosure Crawlspace Type Code</td>
<td align="left">Basement is defined for purposes of the NFIP as any level or story which has its floor subgrade on all sides. Basement structure value are as follow: 0 - None; 1 - Finished Basement/Enclosure;2 - Unfinished Basement/Enclosure;3 - Crawlspace;4 - Subgrade Crawlspace;</td>
<td align="left">number</td>
<td align="left">3</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left"></td>
<td align="left">7b8e36bb14688e9df9005e82bebedfcef0992f4a</td>
<td align="left">2021-09-01T15:01:27.189Z</td>
<td align="left">5f086f3e1dbf327060c5c0c7</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<p>The FEMA API limits the number of records that can be returned in a single query to 1000, meaning if we want more observations than that, a loop is necessary to iterate over multiple API calls. The function handles this automatically, but will warn you before iterating by letting you know how many records there are and how many individual API calls it will take to get all the records. At that point you can enter “1” to continue or “0” to abort the operation. As can be seen below, running <code>open_fema(data_set = "fimaNfipClaims")</code> will indicate that there are over 2.5 million records if we don’t apply any filters to the data set which would take many iterations (and a long time) to collect the full data set.</p>
<pre><code>#&gt; [1] "[1] 2556847 matching records found. At  records per call, it will take 2557 individual API calls to get all matching records. Continue?"
#&gt; [1] "1 - Yes, get that data!, 0 - No, let me rethink my API call:"</code></pre>
<p>Alternatively, we could specify the top_n argument to limit the number of records returned. Specifying top_n greater than 1000 will initiate the same message letting you know how many iterations it will take to get your data. If top_n is less than 1000, the API call will be automatically be carried out. In the case below, we will return the first 10 records from the NFIP Claims data.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipClaims"</span>, top_n <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>
<span class="fu">kable</span><span class="op">(</span><span class="va">df</span><span class="op">)</span></code></pre></div>
<table class="table">
<colgroup>
<col width="3%">
<col width="2%">
<col width="2%">
<col width="3%">
<col width="2%">
<col width="2%">
<col width="1%">
<col width="1%">
<col width="3%">
<col width="2%">
<col width="3%">
<col width="3%">
<col width="2%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="2%">
<col width="2%">
<col width="2%">
<col width="4%">
<col width="2%">
<col width="1%">
<col width="1%">
<col width="2%">
<col width="2%">
<col width="3%">
<col width="3%">
<col width="5%">
<col width="3%">
<col width="1%">
<col width="3%">
<col width="0%">
<col width="3%">
<col width="3%">
<col width="1%">
<col width="1%">
<col width="1%">
<col width="2%">
</colgroup>
<thead><tr class="header">
<th align="left">agricultureStructureIndicator</th>
<th align="left">asOfDate</th>
<th align="left">baseFloodElevation</th>
<th align="left">basementEnclosureCrawlspace</th>
<th align="left">reportedCity</th>
<th align="left">condominiumIndicator</th>
<th align="left">policyCount</th>
<th align="left">countyCode</th>
<th align="left">communityRatingSystemDiscount</th>
<th align="left">dateOfLoss</th>
<th align="left">elevatedBuildingIndicator</th>
<th align="left">elevationCertificateIndicator</th>
<th align="left">elevationDifference</th>
<th align="left">censusTract</th>
<th align="left">floodZone</th>
<th align="left">houseWorship</th>
<th align="left">latitude</th>
<th align="left">longitude</th>
<th align="left">locationOfContents</th>
<th align="left">lowestAdjacentGrade</th>
<th align="left">lowestFloorElevation</th>
<th align="left">numberOfFloorsInTheInsuredBuilding</th>
<th align="left">nonProfitIndicator</th>
<th align="left">obstructionType</th>
<th align="left">occupancyType</th>
<th align="left">originalConstructionDate</th>
<th align="left">originalNBDate</th>
<th align="left">amountPaidOnBuildingClaim</th>
<th align="left">amountPaidOnContentsClaim</th>
<th align="left">amountPaidOnIncreasedCostOfComplianceClaim</th>
<th align="left">postFIRMConstructionIndicator</th>
<th align="left">rateMethod</th>
<th align="left">smallBusinessIndicatorBuilding</th>
<th align="left">state</th>
<th align="left">totalBuildingInsuranceCoverage</th>
<th align="left">totalContentsInsuranceCoverage</th>
<th align="left">yearOfLoss</th>
<th align="left">reportedZipcode</th>
<th align="left">primaryResidence</th>
<th align="left">id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">30009</td>
<td align="left">NULL</td>
<td align="left">2011-07-12T04:00:00.000Z</td>
<td align="left">TRUE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">30009000300</td>
<td align="left">AE</td>
<td align="left">FALSE</td>
<td align="left">45.2</td>
<td align="left">-109.2</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">FALSE</td>
<td align="left">50</td>
<td align="left">1</td>
<td align="left">1975-01-01T05:00:00.000Z</td>
<td align="left">2011-04-13T04:00:00.000Z</td>
<td align="left">593.5</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">FALSE</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">MT</td>
<td align="left">150000</td>
<td align="left">0</td>
<td align="left">2011</td>
<td align="left">59068</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42d1</td>
</tr>
<tr class="even">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">1</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">24033</td>
<td align="left">5</td>
<td align="left">2007-01-01T05:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">24033801600</td>
<td align="left">X</td>
<td align="left">FALSE</td>
<td align="left">38.8</td>
<td align="left">-77.0</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">3</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">1</td>
<td align="left">1953-01-01T05:00:00.000Z</td>
<td align="left">2006-11-15T05:00:00.000Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">FALSE</td>
<td align="left">7</td>
<td align="left">FALSE</td>
<td align="left">MD</td>
<td align="left">100000</td>
<td align="left">40000</td>
<td align="left">2007</td>
<td align="left">20745</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42d0</td>
</tr>
<tr class="odd">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">2</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">29189</td>
<td align="left">NULL</td>
<td align="left">2008-09-13T04:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">29189215700</td>
<td align="left">AE</td>
<td align="left">FALSE</td>
<td align="left">38.7</td>
<td align="left">-90.3</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">1</td>
<td align="left">1957-01-01T05:00:00.000Z</td>
<td align="left">1996-02-08T05:00:00.000Z</td>
<td align="left">118224.96</td>
<td align="left">26300</td>
<td align="left">NULL</td>
<td align="left">FALSE</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">MO</td>
<td align="left">250000</td>
<td align="left">0</td>
<td align="left">2008</td>
<td align="left">63130</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42d6</td>
</tr>
<tr class="even">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">12086</td>
<td align="left">10</td>
<td align="left">1992-08-24T04:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="left">12086008405</td>
<td align="left">AE</td>
<td align="left">FALSE</td>
<td align="left">25.7</td>
<td align="left">-80.3</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">10</td>
<td align="left">1</td>
<td align="left">1988-01-01T05:00:00.000Z</td>
<td align="left">1988-06-15T04:00:00.000Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">TRUE</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">FL</td>
<td align="left">185000</td>
<td align="left">52500</td>
<td align="left">1992</td>
<td align="left">33176</td>
<td align="left">FALSE</td>
<td align="left">6175bc553f4df1156c4c42d7</td>
</tr>
<tr class="odd">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">48201</td>
<td align="left">7</td>
<td align="left">1989-08-01T04:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">48201350400</td>
<td align="left">X</td>
<td align="left">FALSE</td>
<td align="left">29.6</td>
<td align="left">-95.2</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">3</td>
<td align="left">FALSE</td>
<td align="left">10</td>
<td align="left">1</td>
<td align="left">1974-12-31T05:00:00.000Z</td>
<td align="left">1984-12-20T05:00:00.000Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">FALSE</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">TX</td>
<td align="left">88700</td>
<td align="left">25600</td>
<td align="left">1989</td>
<td align="left">77089</td>
<td align="left">FALSE</td>
<td align="left">6175bc553f4df1156c4c42d8</td>
</tr>
<tr class="even">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">51810</td>
<td align="left">7</td>
<td align="left">1998-02-05T05:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">51810045412</td>
<td align="left">X</td>
<td align="left">FALSE</td>
<td align="left">36.7</td>
<td align="left">-75.9</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">FALSE</td>
<td align="left">10</td>
<td align="left">1</td>
<td align="left">1984-07-01T04:00:00.000Z</td>
<td align="left">1988-09-23T04:00:00.000Z</td>
<td align="left">342.57</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">TRUE</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">VA</td>
<td align="left">185000</td>
<td align="left">60000</td>
<td align="left">1998</td>
<td align="left">23456</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42d9</td>
</tr>
<tr class="odd">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">01003</td>
<td align="left">7</td>
<td align="left">2004-09-16T04:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">01003011405</td>
<td align="left">X</td>
<td align="left">FALSE</td>
<td align="left">30.3</td>
<td align="left">-87.5</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">1</td>
<td align="left">1995-01-01T05:00:00.000Z</td>
<td align="left">2002-04-28T04:00:00.000Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">TRUE</td>
<td align="left">7</td>
<td align="left">FALSE</td>
<td align="left">AL</td>
<td align="left">200000</td>
<td align="left">50000</td>
<td align="left">2004</td>
<td align="left">36561</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42de</td>
</tr>
<tr class="even">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">10</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">13051</td>
<td align="left">5</td>
<td align="left">2017-09-11T04:00:00.000Z</td>
<td align="left">TRUE</td>
<td align="left">NULL</td>
<td align="left">2</td>
<td align="left">13051011005</td>
<td align="left">AE</td>
<td align="left">FALSE</td>
<td align="left">31.9</td>
<td align="left">-81.1</td>
<td align="left">0</td>
<td align="left">6.5</td>
<td align="left">12.1</td>
<td align="left">3</td>
<td align="left">FALSE</td>
<td align="left">15</td>
<td align="left">1</td>
<td align="left">2005-01-01T05:00:00.000Z</td>
<td align="left">2006-07-06T04:00:00.000Z</td>
<td align="left">6909.35</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">TRUE</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">GA</td>
<td align="left">250000</td>
<td align="left">100000</td>
<td align="left">2017</td>
<td align="left">31411</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42df</td>
</tr>
<tr class="odd">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">36119</td>
<td align="left">NULL</td>
<td align="left">1999-09-16T04:00:00.000Z</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">36119014809</td>
<td align="left">X</td>
<td align="left">FALSE</td>
<td align="left">41.3</td>
<td align="left">-73.8</td>
<td align="left">0</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">FALSE</td>
<td align="left">10</td>
<td align="left">1</td>
<td align="left">1973-01-01T05:00:00.000Z</td>
<td align="left">1996-02-07T05:00:00.000Z</td>
<td align="left">15871.1</td>
<td align="left">12754.6</td>
<td align="left">NULL</td>
<td align="left">FALSE</td>
<td align="left">7</td>
<td align="left">FALSE</td>
<td align="left">NY</td>
<td align="left">150000</td>
<td align="left">38000</td>
<td align="left">1999</td>
<td align="left">10598</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42e3</td>
</tr>
<tr class="even">
<td align="left">FALSE</td>
<td align="left">2021-07-25T01:39:04.381Z</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">Temporarily Unavailable</td>
<td align="left">N</td>
<td align="left">1</td>
<td align="left">37191</td>
<td align="left">8</td>
<td align="left">2018-10-10T04:00:00.000Z</td>
<td align="left">TRUE</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">37191000102</td>
<td align="left">X</td>
<td align="left">FALSE</td>
<td align="left">35.5</td>
<td align="left">-78.0</td>
<td align="left">7</td>
<td align="left">NULL</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">1</td>
<td align="left">2007-01-01T05:00:00.000Z</td>
<td align="left">2009-07-31T04:00:00.000Z</td>
<td align="left">9880.9</td>
<td align="left">NULL</td>
<td align="left">NULL</td>
<td align="left">TRUE</td>
<td align="left">7</td>
<td align="left">FALSE</td>
<td align="left">NC</td>
<td align="left">250000</td>
<td align="left">100000</td>
<td align="left">2018</td>
<td align="left">27863</td>
<td align="left">TRUE</td>
<td align="left">6175bc553f4df1156c4c42e4</td>
</tr>
</tbody>
</table>
<p>If we wanted to limit the columns returned we could do so by passing a character vector of data fields to be included in the returned data frame. The data fields for a given data set can be retrieved using the <code><a href="../reference/fema_data_fields.html">fema_data_fields()</a></code> function.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">data_fields</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/fema_data_fields.html">fema_data_fields</a></span><span class="op">(</span><span class="st">"fimanfipclaims"</span><span class="op">)</span>
<span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_fields</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<table class="table">
<colgroup>
<col width="0%">
<col width="2%">
<col width="3%">
<col width="1%">
<col width="6%">
<col width="6%">
<col width="46%">
<col width="2%">
<col width="3%">
<col width="1%">
<col width="2%">
<col width="3%">
<col width="2%">
<col width="6%">
<col width="5%">
<col width="5%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="left">datasetId</th>
<th align="left">openFemaDataSet</th>
<th align="left">name</th>
<th align="left">title</th>
<th align="left">description</th>
<th align="left">type</th>
<th align="left">sortOrder</th>
<th align="left">datasetVersion</th>
<th align="left">hash</th>
<th align="left">lastRefresh</th>
<th align="left">isNestedObject</th>
<th align="left">isNullable</th>
<th align="left">isSearchable</th>
<th align="left">primaryKey</th>
<th align="left">id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">659</td>
<td align="left">openfema-31</td>
<td align="left">FimaNfipClaims</td>
<td align="left">1</td>
<td align="left">agricultureStructureIndicator</td>
<td align="left">Agriculture Structure Indicator</td>
<td align="left">Yes (Y) or No (N) indicator of whether or not a building is reported as being an agricultural structure in the policy application. Yes is indicated with either a ‘true’ or ‘1’. No is indicated with either a ‘false’ or ‘0’</td>
<td align="left">boolean</td>
<td align="left">1</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">fc0a16c05dd1debdc1b59044d17e0dd5</td>
<td align="left">2020-07-10T13:38:06.080Z</td>
<td align="left">5f086f3e1dbf327060c5c09d</td>
</tr>
<tr class="even">
<td align="left">660</td>
<td align="left">openfema-31</td>
<td align="left">FimaNfipClaims</td>
<td align="left">1</td>
<td align="left">asOfDate</td>
<td align="left">As Of Date</td>
<td align="left">The effective date of the data in the file. When time is not specified in the field, it will default to T00:00:00.000Z</td>
<td align="left">date</td>
<td align="left">2</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">d97ebf6a1c5f6400506955b2b9b95773</td>
<td align="left">2020-07-10T13:38:06.083Z</td>
<td align="left">5f086f3e1dbf327060c5c09e</td>
</tr>
<tr class="odd">
<td align="left">661</td>
<td align="left">openfema-31</td>
<td align="left">FimaNfipClaims</td>
<td align="left">1</td>
<td align="left">baseFloodElevation</td>
<td align="left">Base Flood Elevation</td>
<td align="left">Base Flood Elevation (BFE) is the elevation at which there is a 1% chance per year of flooding in feet from the elevation certificate</td>
<td align="left">number</td>
<td align="left">3</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left">NULL</td>
<td align="left">c24a4e559d89d8f064e2a294a803bf73</td>
<td align="left">2020-07-10T13:38:06.084Z</td>
<td align="left">5f086f3e1dbf327060c5c09f</td>
</tr>
</tbody>
</table>
<p>In this case we will return only the <code>policyCount</code> and <code>floodZone</code> columns. As can be seen, an id column is always returned even if the select argument is used.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipClaims"</span>, top_n <span class="op">=</span> <span class="fl">10</span>, select <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"policyCount"</span>,<span class="st">"floodZone"</span><span class="op">)</span><span class="op">)</span>
<span class="fu">kable</span><span class="op">(</span><span class="va">df</span><span class="op">)</span></code></pre></div>
<table class="table">
<thead><tr class="header">
<th align="left">policyCount</th>
<th align="left">floodZone</th>
<th align="left">id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">AE</td>
<td align="left">6175bc553f4df1156c4c42d1</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">X</td>
<td align="left">6175bc553f4df1156c4c42d0</td>
</tr>
<tr class="odd">
<td align="left">1</td>
<td align="left">AE</td>
<td align="left">6175bc553f4df1156c4c42d6</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">AE</td>
<td align="left">6175bc553f4df1156c4c42d7</td>
</tr>
<tr class="odd">
<td align="left">1</td>
<td align="left">X</td>
<td align="left">6175bc553f4df1156c4c42d8</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">X</td>
<td align="left">6175bc553f4df1156c4c42d9</td>
</tr>
<tr class="odd">
<td align="left">1</td>
<td align="left">X</td>
<td align="left">6175bc553f4df1156c4c42de</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">AE</td>
<td align="left">6175bc553f4df1156c4c42df</td>
</tr>
<tr class="odd">
<td align="left">1</td>
<td align="left">X</td>
<td align="left">6175bc553f4df1156c4c42e3</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">X</td>
<td align="left">6175bc553f4df1156c4c42e4</td>
</tr>
</tbody>
</table>
<p>If we want to limit the rows returned rather than the columns, we can also apply filters by specifying values of the columns to return. If we want to quickly see the set of variables that can be used to filter API queries with, we can use the valid_parameters() function to return a vector containing the variables that are “searchable” for a particular data set.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">params</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/valid_parameters.html">valid_parameters</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipClaims"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">params</span>, collapse <span class="op">=</span> <span class="st">", "</span><span class="op">)</span>
<span class="co">#&gt; [1] "agricultureStructureIndicator, asOfDate, baseFloodElevation, basementEnclosureCrawlspaceType, reportedCity, condominiumIndicator , policyCount, countyCode , communityRatingSystemDiscount, dateOfLoss, elevatedBuildingIndicator, elevationDifference, elevationCertificateIndicator, censusTract, floodZone, latitude, houseWorship, locationOfContents, longitude, lowestAdjacentGrade, lowestFloorElevation, numberOfFloorsInTheInsuredBuilding, nonProfitIndicator, obstructionType, occupancyType, originalNBDate, originalConstructionDate, amountPaidOnBuildingClaim, amountPaidOnContentsClaim, postFIRMConstructionIndicator, amountPaidOnIncreasedCostOfComplianceClaim, rateMethod, smallBusinessIndicatorBuilding, state, totalBuildingInsuranceCoverage, totalContentsInsuranceCoverage, yearofLoss, reportedZipCode, primaryResidence, id, yearOfLoss"</span></code></pre></div>
<p>We can see from the above that both <code>policyCount</code> and <code>floodZone</code> are both searchable variables. Thus we can specify a list that contains the values of each variable that we want returned in the data frame. Before doing that however, it can be useful to see unique values of those variables in the data set. We can do this by using the <code><a href="../reference/parameter_values.html">parameter_values()</a></code> function. This function returns the unique values of a variable contained in the first 1000 observations of a data set. Notably, it does not return all unique values, as that would require access to the entire data set, which as we saw above is over 2.5 million records.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/parameter_values.html">parameter_values</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipClaims"</span>,data_field <span class="op">=</span> <span class="st">"floodZone"</span><span class="op">)</span>
<span class="co">#&gt;  [1] "AE"   "X"    "C"    "AHB"  "A99"  "A11"  "A"    "A08"  "AOB"  "A06" </span>
<span class="co">#&gt; [11] "AH"   "A04"  "VE"   "V21"  "A07"  "A10"  "A14"  "A01"  "A17"  "B"   </span>
<span class="co">#&gt; [21] "D"    "AO"   "A09"  "A02"  "V11"  "A05"  "A15"  "A12"  "A16"  "A03" </span>
<span class="co">#&gt; [31] "V13"  "NULL"</span></code></pre></div>
<p>We can see from the above that <code>floodZone</code> is a character in the data and there are 32 unique values in the first 1000 observations of the full data set. Lets go a head a define a filter to limit our results to records with “AE” or “X” flood zones.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_filters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>floodZone <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"AE"</span>,<span class="st">"X"</span><span class="op">)</span><span class="op">)</span>

<span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipPolicies"</span>, top_n <span class="op">=</span> <span class="fl">10</span>, 
               select <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"policyCount"</span>,<span class="st">"floodZone"</span><span class="op">)</span>, filters <span class="op">=</span> <span class="va">my_filters</span><span class="op">)</span>
<span class="fu">kable</span><span class="op">(</span><span class="va">df</span><span class="op">)</span></code></pre></div>
<table class="table">
<thead><tr class="header">
<th align="left">floodZone</th>
<th align="left">policyCount</th>
<th align="left">id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffeef6</td>
</tr>
<tr class="even">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef03</td>
</tr>
<tr class="odd">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef0f</td>
</tr>
<tr class="even">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef11</td>
</tr>
<tr class="odd">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef1a</td>
</tr>
<tr class="even">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef44</td>
</tr>
<tr class="odd">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef47</td>
</tr>
<tr class="even">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef48</td>
</tr>
<tr class="odd">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef51</td>
</tr>
<tr class="even">
<td align="left">AE</td>
<td align="left">1</td>
<td align="left">6177019153bce8619fffef87</td>
</tr>
</tbody>
</table>
</div>
<div id="more-examples" class="section level2">
<h2 class="hasAnchor">
<a href="#more-examples" class="anchor"></a>More Examples</h2>
<div id="example-return-the-first-100-nfip-claims-for-autauga-county-al-that-happened-between-2010-and-2020-" class="section level3">
<h3 class="hasAnchor">
<a href="#example-return-the-first-100-nfip-claims-for-autauga-county-al-that-happened-between-2010-and-2020-" class="anchor"></a>Example: Return the first 100 NFIP claims for Autauga County, AL that happened between 2010 and 2020.</h3>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"fimaNfipClaims"</span>,
                 top_n <span class="op">=</span> <span class="fl">100</span>,
                 filters <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>countyCode <span class="op">=</span> <span class="st">"= 01001"</span>,
                                yearOfLoss <span class="op">=</span> <span class="st">"&gt;= 2010"</span>,
                                yearOfLoss <span class="op">=</span> <span class="st">"&lt;= 2020"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
</div>
<div id="example-get-data-on-all-hazard-mitigation-grants-associated-with-hurricanes-in-florida-" class="section level3">
<h3 class="hasAnchor">
<a href="#example-get-data-on-all-hazard-mitigation-grants-associated-with-hurricanes-in-florida-" class="anchor"></a>Example: Get data on all Hazard Mitigation Grants associated with Hurricanes in Florida.</h3>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># see which parameter can be used for filtering the Hazard Mitigation Grants data set</span>
<span class="fu"><a href="../reference/valid_parameters.html">valid_parameters</a></span><span class="op">(</span><span class="st">"HazardMitigationGrants"</span><span class="op">)</span> 
<span class="co">#&gt;  [1] "id"                  "projectType"         "projectCounties"    </span>
<span class="co">#&gt;  [4] "status"              "subgrantee"          "disasterNumber"     </span>
<span class="co">#&gt;  [7] "state"               "projectAmount"       "region"             </span>
<span class="co">#&gt; [10] "declarationDate"     "projectNumber"       "disasterTitle"      </span>
<span class="co">#&gt; [13] "projectDescription"  "lastRefresh"         "costSharePercentage"</span>
<span class="co">#&gt; [16] "subgranteeFIPSCode"  "projectTitle"        "incidentType"       </span>
<span class="co">#&gt; [19] "hash"</span>

<span class="co"># check example values for "incidentType"</span>
<span class="fu"><a href="../reference/parameter_values.html">parameter_values</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"HazardMitigationGrants"</span>, data_field <span class="op">=</span> <span class="st">"incidentType"</span><span class="op">)</span> 
<span class="co">#&gt;  [1] "Flood"            "Severe Storm(s)"  "Tornado"          "Freezing"        </span>
<span class="co">#&gt;  [5] "Hurricane"        "Earthquake"       "Typhoon"          "Volcano"         </span>
<span class="co">#&gt;  [9] "Fire"             "Snow"             "Severe Ice Storm" "Coastal Storm"</span>

<span class="co"># check to see how "state" is formatted</span>
<span class="fu"><a href="../reference/parameter_values.html">parameter_values</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"HazardMitigationGrants"</span>, data_field <span class="op">=</span> <span class="st">"state"</span><span class="op">)</span> 
<span class="co">#&gt;  [1] "Kentucky"                       "Utah"                          </span>
<span class="co">#&gt;  [3] "North Dakota"                   "Texas"                         </span>
<span class="co">#&gt;  [5] "North Carolina"                 "Alaska"                        </span>
<span class="co">#&gt;  [7] "Connecticut"                    "Virgin Islands of the U.S."    </span>
<span class="co">#&gt;  [9] "Louisiana"                      "Vermont"                       </span>
<span class="co">#&gt; [11] "Puerto Rico"                    "South Carolina"                </span>
<span class="co">#&gt; [13] "Maine"                          "Maryland"                      </span>
<span class="co">#&gt; [15] "Minnesota"                      "Washington"                    </span>
<span class="co">#&gt; [17] "District of Columbia"           "California"                    </span>
<span class="co">#&gt; [19] "Virginia"                       "Alabama"                       </span>
<span class="co">#&gt; [21] "Mississippi"                    "Northern Mariana Islands"      </span>
<span class="co">#&gt; [23] "Tennessee"                      "Oregon"                        </span>
<span class="co">#&gt; [25] "Georgia"                        "Hawaii"                        </span>
<span class="co">#&gt; [27] "American Samoa"                 "Arkansas"                      </span>
<span class="co">#&gt; [29] "Oklahoma"                       "Missouri"                      </span>
<span class="co">#&gt; [31] "Iowa"                           "Nebraska"                      </span>
<span class="co">#&gt; [33] "New Hampshire"                  "Wisconsin"                     </span>
<span class="co">#&gt; [35] "Illinois"                       "Indiana"                       </span>
<span class="co">#&gt; [37] "Palau"                          "Ohio"                          </span>
<span class="co">#&gt; [39] "Federated States of Micronesia" "Arizona"                       </span>
<span class="co">#&gt; [41] "Guam"                           "New York"                      </span>
<span class="co">#&gt; [43] "Rhode Island"                   "Massachusetts"                 </span>
<span class="co">#&gt; [45] "Marshall Islands"</span>

<span class="co"># construct a list containing filters for Hurricane and Florida</span>
<span class="va">filter_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>incidentType <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Hurricane"</span><span class="op">)</span>,
                 state <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Florida"</span><span class="op">)</span><span class="op">)</span> 

<span class="co"># pass filter_list to the open_fema function to retreieve data.</span>
<span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"HazardMitigationGrants"</span>, filters <span class="op">=</span> <span class="va">filter_list</span>, 
               ask_before_call <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="co">#&gt; 1 out of 2 itterations completedFALSE</span>
<span class="co">#&gt; 2 out of 2 itterations completedFALSE</span>
<span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<table class="table">
<colgroup>
<col width="1%">
<col width="1%">
<col width="2%">
<col width="3%">
<col width="1%">
<col width="2%">
<col width="2%">
<col width="8%">
<col width="6%">
<col width="40%">
<col width="2%">
<col width="3%">
<col width="3%">
<col width="2%">
<col width="2%">
<col width="2%">
<col width="4%">
<col width="3%">
<col width="3%">
</colgroup>
<thead><tr class="header">
<th align="left">region</th>
<th align="left">state</th>
<th align="left">disasterNumber</th>
<th align="left">declarationDate</th>
<th align="left">incidentType</th>
<th align="left">disasterTitle</th>
<th align="left">projectNumber</th>
<th align="left">projectType</th>
<th align="left">projectTitle</th>
<th align="left">projectDescription</th>
<th align="left">projectCounties</th>
<th align="left">status</th>
<th align="left">subgrantee</th>
<th align="left">subgranteeFIPSCode</th>
<th align="left">projectAmount</th>
<th align="left">costSharePercentage</th>
<th align="left">hash</th>
<th align="left">lastRefresh</th>
<th align="left">id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">4</td>
<td align="left">Florida</td>
<td align="left">955</td>
<td align="left">1992-08-24T00:00:00.000Z</td>
<td align="left">Hurricane</td>
<td align="left">HURRICANE ANDREW</td>
<td align="left">0004</td>
<td align="left">401.1: Water and Sanitary Sewer System Protective Measures</td>
<td align="left">GIS UTILITY RESPONSE DATA FILES</td>
<td align="left">Load all water and sewer lines onto a GIS and field locate essential facilities to shorten repair crew response time.</td>
<td align="left">BROWARD</td>
<td align="left">Not Approved / Denied</td>
<td align="left">BROWARD COUNTY</td>
<td align="left">1100000</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">bd8da6fb6e52916e3c822f4aca8b7f82</td>
<td align="left">2017-12-11T16:09:24.558Z</td>
<td align="left">5a2eadb4758c6e4347f37aa1</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">Florida</td>
<td align="left">955</td>
<td align="left">1992-08-24T00:00:00.000Z</td>
<td align="left">Hurricane</td>
<td align="left">HURRICANE ANDREW</td>
<td align="left">0002</td>
<td align="left">205.8: Retrofitting Public Structures - Wind</td>
<td align="left">WIND RETROFIT BLDG - REINFORCE GLASS WALLS</td>
<td align="left">Protect building with laminated glass, shuttering, bracing, rollup doors, and skylight retrofit .</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>See Comments section for further description. |BROWARD |Closed |PERFORMING ARTS CENT |1190704 |1687412 |50 |7662a07458802ded73f1e5555c16d06e |2017-12-11T16:12:06.413Z |5a2eadb4758c6e4347f37ac1 | |4 |Florida |955 |1992-08-24T00:00:00.000Z |Hurricane |HURRICANE ANDREW |0003 |501.1: Other Major Structural Projects |REPLACE TRAFFIC SIGNALS/ELEVATE CONTROL BOXES |Replace span wire traffic signals with mast arm installations. Raise control cabinets to prevent water intrusion and flooding. |BROWARD |Withdrawn |BROWARD COUNTY |1100000 |0 |0 |cbe2884b62ee5a92052adcd72b7548ad |2017-12-11T16:09:24.575Z |5a2eadb4758c6e4347f37ad4 | |4 |Florida |955 |1992-08-24T00:00:00.000Z |Hurricane |HURRICANE ANDREW |0001 |602.1: Other Equipment Purchase and Installation |RECOVERY MANAGEMENT PROJECT |Proposed system funding levels: Hardware: $670,000, Software: $55,000, Training: $60,000; system customization: $200,000; maintenance: $110,000; data acquistion: $325,000; Miami DFO and four county disaster area support: $180,000, for a total of : $1,600,000. |STATEWIDE |Closed |DEPARTMENT OF COMMUN |92040 |1600000 |50 |2a1e5ea264fb4ec92c8244db0829e09a |2017-12-11T16:09:24.586Z |5a2eadb4758c6e4347f37af5 | |4 |Florida |955 |1992-08-24T00:00:00.000Z |Hurricane |HURRICANE ANDREW |0019 |205.8: Retrofitting Public Structures - Wind |WIND RETROFIT BLDGS - SHUTTERS |Install shutters over all openings to public works maintenance building to prevent damage from hurricane winds. This project plans to install 183 SF of shutters at all window openings for an estimated cost of $1,400. |BROWARD |Closed |LIGHTHOUSE POINT |1140450 |1500 |50 |55eaf4535a6f0a5264991d722469054a |2017-12-11T16:09:24.849Z |5a2eadb4758c6e4347f37af9 | |4 |Florida |955 |1992-08-24T00:00:00.000Z |Hurricane |HURRICANE ANDREW |0014 |601.1: Generators |ELEVATE/RELOCATE EMERGENCY GENERATOR |Construct engine / generator set enclosure at an alternative location above minimum floodplain elevation, together with extension of primary feeders to emergency switch gear, to prevent flooding during a storm event. |BROWARD |Withdrawn |DAVIE |1116475 |0 |0 |9986bc5b602bc4b7c2450514d62ce5e2 |2017-12-11T16:09:24.849Z |5a2eadb4758c6e4347f37af8 |</p>
</div>
<div id="example-determine-how-much-money-was-awarded-by-fema-for-rental-assistance-following-hurricane-irma-" class="section level3">
<h3 class="hasAnchor">
<a href="#example-determine-how-much-money-was-awarded-by-fema-for-rental-assistance-following-hurricane-irma-" class="anchor"></a>Example: Determine how much money was awarded by FEMA for rental assistance following Hurricane Irma.</h3>
<p>Get a dataset description for the <code>HousingAssistanceRenters</code> data set to see if this is the right data set for the question</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get meta data for the `HousingAssistanceRenters`</span>
<span class="va">ds</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/fema_data_sets.html">fema_data_sets</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">name</span> <span class="op">==</span> <span class="st">"HousingAssistanceRenters"</span><span class="op">)</span>

<span class="co"># there are two entries corresponding to two versions of the data set, </span>
<span class="co"># we want the most recent one</span>
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">ds</span><span class="op">)</span>
<span class="co">#&gt; [1] 2</span>
<span class="va">ds</span> <span class="op">&lt;-</span> <span class="va">ds</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">version</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">ds</span><span class="op">$</span><span class="va">version</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="co"># now print out the data set description</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">ds</span><span class="op">$</span><span class="va">description</span><span class="op">)</span>
<span class="co">#&gt; [1] "The dataset was generated by FEMA's Enterprise Coordination &amp; Information Management (ECIM) Reporting team and is primarily composed of data from Housing Assistance Program reporting authority from FEMA registration renters and owners within the state, county, zip where the registration is valid. This dataset contains aggregated, non-PII data on FEMA's Housing Assistance Program within the state, county, zip where the registration is valid for the declarations, starting with disaster declarations number 4116.  The data is divided into data for renters and data for property owners. Additional core data elements include number of applicants, county, zip code, severity of damage, owner or renter. Data is self-reported and as such is subject to human error. To learn more about disaster assistance please visit https://www.fema.gov/individual-disaster-assistance.This is raw, unedited data from FEMA's National Emergency Management Information System (NEMIS) and as such is subject to a small percentage of human error. For example, when an applicant registers they enter their street and city address.  The system runs a check and suggests a county.  The applicant, if registering online can override that choice.  If they are registering via the call center the Human Services Specialist (HSS) representatives are instructed to ask (not offer) what county they live in.  So even though the system might suggest County A,  an applicant has the right to choose County B.  The financial information is derived from NEMIS and not FEMA's official financial systems.  Due to differences in reporting periods, status of obligations and how business rules are applied, this financial information may differ slightly from official publication on public websites such as usaspending.gov;  this dataset is not intended to be used for any official federal financial reporting.Citation: The Agency's preferred citation for datasets (API usage or file downloads) can be found on the OpenFEMA Terms and Conditions page, Citing Data section: https://www.fema.gov/about/openfema/terms-conditions.If you have media inquiries about this dataset, please email the FEMA News Desk FEMA-News-Desk@dhs.gov or call (202) 646-3272.  For inquiries about FEMA's data and Open government program please contact the OpenFEMA team via email OpenFEMA@fema.dhs.gov."</span></code></pre></div>
<p>See which columns we can filter on to select just Hurricane Irma related grants</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># see which parameter can be used for filtering the Housing Assistance for Renters </span>
<span class="fu"><a href="../reference/valid_parameters.html">valid_parameters</a></span><span class="op">(</span><span class="st">"HousingAssistanceRenters"</span><span class="op">)</span> 
<span class="co">#&gt;  [1] "city"                         "validRegistrations"          </span>
<span class="co">#&gt;  [3] "disasterNumber"               "zipCode"                     </span>
<span class="co">#&gt;  [5] "repairReplaceAmount"          "totalInspected"              </span>
<span class="co">#&gt;  [7] "approvedForFemaAssistance"    "totalWithSubstantialDamage"  </span>
<span class="co">#&gt;  [9] "rentalAmount"                 "otherNeedsAmount"            </span>
<span class="co">#&gt; [11] "approvedBetween10001And25000" "totalInspectedWithNoDamage"  </span>
<span class="co">#&gt; [13] "approvedBetween1And10000"     "approvedBetween25001AndMax"  </span>
<span class="co">#&gt; [15] "totalMaxGrants"               "hash"                        </span>
<span class="co">#&gt; [17] "lastRefresh"                  "county"                      </span>
<span class="co">#&gt; [19] "state"                        "totalWithModerateDamage"     </span>
<span class="co">#&gt; [21] "totalApprovedIhpAmount"       "totalWithMajorDamage"        </span>
<span class="co">#&gt; [23] "id"                           "2"                           </span>
<span class="co">#&gt; [25] "2"                            "2"                           </span>
<span class="co">#&gt; [27] "2"                            "2"                           </span>
<span class="co">#&gt; [29] "2"                            "2"                           </span>
<span class="co">#&gt; [31] "2"                            "2"                           </span>
<span class="co">#&gt; [33] "2"                            "2"                           </span>
<span class="co">#&gt; [35] "2"                            "2"                           </span>
<span class="co">#&gt; [37] "2"                            "2"                           </span>
<span class="co">#&gt; [39] "2"                            "2"                           </span>
<span class="co">#&gt; [41] "2"                            "2"                           </span>
<span class="co">#&gt; [43] "2"                            "2"</span></code></pre></div>
<p>All we have in this data set is the <code>disasterNumber</code>. Thus, to filter on a specific disaster we have to load the <code>FemaWebDisasterDeclarations</code> data find the disaster number associated with the event we are interested in.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># call the disaster declarations</span>
<span class="va">dd</span> <span class="op">&lt;-</span> <span class="fu">rfema</span><span class="fu">::</span><span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"FemaWebDisasterDeclarations"</span>, ask_before_call <span class="op">=</span> <span class="cn">F</span><span class="op">)</span>
<span class="co">#&gt; 1 out of 5 itterations completedFALSE</span>
<span class="co">#&gt; 2 out of 5 itterations completedFALSE</span>
<span class="co">#&gt; 3 out of 5 itterations completedFALSE</span>
<span class="co">#&gt; 4 out of 5 itterations completedFALSE</span>
<span class="co">#&gt; 5 out of 5 itterations completedFALSE</span>

<span class="co"># filter disaster declarations to those with "hurricane" in the name</span>
<span class="va">hurricanes</span> <span class="op">&lt;-</span> <span class="fu">distinct</span><span class="op">(</span><span class="va">dd</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"hurricane"</span>,<span class="fu"><a href="https://rdrr.io/r/base/chartr.html">tolower</a></span><span class="op">(</span><span class="va">disasterName</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu">select</span><span class="op">(</span><span class="va">disasterName</span>, <span class="va">disasterNumber</span><span class="op">)</span><span class="op">)</span>
<span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">hurricanes</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<table class="table">
<thead><tr class="header">
<th align="left">disasterName</th>
<th align="left">disasterNumber</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">HURRICANE MARIA</td>
<td align="left">3390</td>
</tr>
<tr class="even">
<td align="left">HURRICANE IRMA</td>
<td align="left">3388</td>
</tr>
<tr class="odd">
<td align="left">HURRICANE NATE</td>
<td align="left">3395</td>
</tr>
<tr class="even">
<td align="left">HURRICANE HARVEY</td>
<td align="left">4332</td>
</tr>
<tr class="odd">
<td align="left">HURRICANE IRMA</td>
<td align="left">3384</td>
</tr>
<tr class="even">
<td align="left">HURRICANE IRMA - SEMINOLE TRIBE OF FLORIDA</td>
<td align="left">4341</td>
</tr>
</tbody>
</table>
<p>As can be seen, disaster numbers do not uniquely ID an event, since multiple disaster declarations may be declared for the same event, but in different locations. Thus to filter on a particular event, we need to collect all the disaster declaration numbers corresponding to that event.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get all disaster declarations associated with hurricane irma. </span>
<span class="co"># notice the use of grepl() which picked up a disaster declaration name </span>
<span class="co"># that was differnt than all the others.</span>
<span class="va">dd_irma</span> <span class="op">&lt;-</span> <span class="va">hurricanes</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"irma"</span>,<span class="fu"><a href="https://rdrr.io/r/base/chartr.html">tolower</a></span><span class="op">(</span><span class="va">disasterName</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="co"># get a vector of just the disaster declaration numbers</span>
<span class="va">dd_nums_irma</span> <span class="op">&lt;-</span> <span class="va">dd_irma</span><span class="op">$</span><span class="va">disasterNumber</span></code></pre></div>
<p>Now we are read to filter our API call for the <code>HousingAssistanceRenters</code> data set.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># construct filter list</span>
<span class="va">filter_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>disasterNumber <span class="op">=</span> <span class="va">dd_nums_irma</span><span class="op">)</span>


<span class="co"># make the API call to get individual assistance grants awarded to renters for hurricane Irma damages.</span>
<span class="va">assistance_irma</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/open_fema.html">open_fema</a></span><span class="op">(</span>data_set <span class="op">=</span> <span class="st">"HousingAssistanceRenters"</span>, filters <span class="op">=</span> <span class="va">filter_list</span>, ask_before_call <span class="op">=</span> <span class="cn">F</span><span class="op">)</span>
<span class="co">#&gt; 1 out of 6 itterations completedFALSE</span>
<span class="co">#&gt; 2 out of 6 itterations completedFALSE</span>
<span class="co">#&gt; 3 out of 6 itterations completedFALSE</span>
<span class="co">#&gt; 4 out of 6 itterations completedFALSE</span>
<span class="co">#&gt; 5 out of 6 itterations completedFALSE</span>
<span class="co">#&gt; 6 out of 6 itterations completedFALSE</span></code></pre></div>
<p>Check out the returned data</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># check out the returned data</span>
<span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">assistance_irma</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<table class="table">
<colgroup>
<col width="1%">
<col width="4%">
<col width="3%">
<col width="6%">
<col width="5%">
<col width="4%">
<col width="6%">
<col width="5%">
<col width="5%">
<col width="4%">
<col width="2%">
<col width="3%">
<col width="5%">
<col width="6%">
<col width="6%">
<col width="3%">
<col width="3%">
<col width="1%">
<col width="8%">
<col width="6%">
<col width="5%">
</colgroup>
<thead><tr class="header">
<th align="left">state</th>
<th align="left">validRegistrations</th>
<th align="left">totalInspected</th>
<th align="left">totalInspectedWithNoDamage</th>
<th align="left">totalWithModerateDamage</th>
<th align="left">totalWithMajorDamage</th>
<th align="left">totalWithSubstantialDamage</th>
<th align="left">approvedForFemaAssistance</th>
<th align="left">totalApprovedIhpAmount</th>
<th align="left">repairReplaceAmount</th>
<th align="left">rentalAmount</th>
<th align="left">otherNeedsAmount</th>
<th align="left">approvedBetween1And10000</th>
<th align="left">approvedBetween10001And25000</th>
<th align="left">approvedBetween25001AndMax</th>
<th align="left">totalMaxGrants</th>
<th align="left">disasterNumber</th>
<th align="left">zipCode</th>
<th align="left">county</th>
<th align="left">city</th>
<th align="left">id</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">VI</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">2538.06</td>
<td align="left">0</td>
<td align="left">848</td>
<td align="left">1690.06</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4335</td>
<td align="left">00801</td>
<td align="left">St. Thomas (Island) (County-equivalent)</td>
<td align="left">CHARLOTTE AMALIE ST THOMAS</td>
<td align="left">617d043e0e7a7c6db4f87617</td>
</tr>
<tr class="even">
<td align="left">VI</td>
<td align="left">7</td>
<td align="left">6</td>
<td align="left">7</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">16171.25</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">16171.25</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4335</td>
<td align="left">00801</td>
<td align="left">St. Thomas (Island) (County-equivalent)</td>
<td align="left">SAINT THOMAS</td>
<td align="left">617d043e0e7a7c6db4f87619</td>
</tr>
<tr class="odd">
<td align="left">VI</td>
<td align="left">219</td>
<td align="left">181</td>
<td align="left">142</td>
<td align="left">66</td>
<td align="left">10</td>
<td align="left">0</td>
<td align="left">126</td>
<td align="left">366097.13</td>
<td align="left">0</td>
<td align="left">154971</td>
<td align="left">211126.13</td>
<td align="left">124</td>
<td align="left">2</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4335</td>
<td align="left">00801</td>
<td align="left">St. Thomas (Island) (County-equivalent)</td>
<td align="left">ST THOMAS</td>
<td align="left">617d043e0e7a7c6db4f8761a</td>
</tr>
<tr class="even">
<td align="left">VI</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">2</td>
<td align="left">3252.77</td>
<td align="left">0</td>
<td align="left">1696</td>
<td align="left">1556.77</td>
<td align="left">2</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4335</td>
<td align="left">00802</td>
<td align="left">St. Thomas (Island) (County-equivalent)</td>
<td align="left">CHARLOTTE AMA</td>
<td align="left">617d043e0e7a7c6db4f87625</td>
</tr>
<tr class="odd">
<td align="left">VI</td>
<td align="left">4</td>
<td align="left">4</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4</td>
<td align="left">6360</td>
<td align="left">0</td>
<td align="left">5860</td>
<td align="left">500</td>
<td align="left">4</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4335</td>
<td align="left">00802</td>
<td align="left">St. Thomas (Island) (County-equivalent)</td>
<td align="left">CHARLOTTE AMALIE ST THOMAS</td>
<td align="left">617d043e0e7a7c6db4f87627</td>
</tr>
<tr class="even">
<td align="left">VI</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">16957.27</td>
<td align="left">0</td>
<td align="left">8173</td>
<td align="left">8784.27</td>
<td align="left">0</td>
<td align="left">1</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">4335</td>
<td align="left">00802</td>
<td align="left">St. Thomas (Island) (County-equivalent)</td>
<td align="left">CHARLOTTE AMALIE, ST THOMAS</td>
<td align="left">617d043e0e7a7c6db4f87628</td>
</tr>
</tbody>
</table>
<p>Now we can answer our origonal question: How much did FEMA awarded for rental assistance following Hurricane Irma?</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># sum the rentalAmount Column</span>
<span class="va">rent_assistance</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">assistance_irma</span><span class="op">$</span><span class="va">rentalAmount</span><span class="op">)</span><span class="op">)</span>

<span class="co"># scale to millions</span>
<span class="va">rent_assistance</span> <span class="op">&lt;-</span> <span class="va">rent_assistance</span><span class="op">/</span><span class="fl">1000000</span>

<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"$"</span>,<span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">rent_assistance</span>,<span class="fl">2</span><span class="op">)</span>,<span class="st">" million was awarded by FEMA for rental assistance following Hurricane Irma"</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; [1] "$314.64 million was awarded by FEMA for rental assistance following Hurricane Irma"</span></code></pre></div>
</div>
</div>
<div id="bulk-downloads" class="section level2">
<h2 class="hasAnchor">
<a href="#bulk-downloads" class="anchor"></a>Bulk Downloads</h2>
<p>In some cases bulk downloading a full data set file may be preferred. In this case, users can use the bulk_dl() command to download a csv of the full data file and save it to a specified directory.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/bulk_dl.html">bulk_dl</a></span><span class="op">(</span><span class="st">"femaRegions"</span><span class="op">)</span> <span class="co"># download a csv file containing all info on FEMA regions</span>
<span class="co">#&gt; Downloading file to /home/dylan/Dropbox/rfema/vignettes/FemaRegions.csv</span></code></pre></div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Dylan Turner.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
