name: JOSS Paper Compilation
on: [push, pull_request]
jobs:
  compile-paper:
    runs-on: ubuntu-latest
    name: Compile JOSS Paper
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate PDF
        uses: openjournals/paper-action@v1
        with:
          journal: joss
          paper-path: paper.md
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf